import Content from "components/Content/Content";
import Header from "components/Header/Header";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/pages/Home.module.scss";

export default function Home() {
  return (
    <div>
      <Head>
        <title>TeeRex Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
    </div>
  );
}
